packages:
  - cli
  - packages/*

minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@shbernal/*'

allowBuilds:
  '@google/genai': true
  esbuild: true
  lefthook: true
  protobufjs: true

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - protobufjs
  - zipfile
