packages:
  - cli
  - packages/*

minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@ankimd/*'
  - '@shbernal/*'
  - flashcard-md-spec@1.0.0

allowBuilds:
  '@google/genai': true
  esbuild: true
  lefthook: true
  protobufjs: true

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - protobufjs
  - zipfile
